version: '3'
services:
  flask-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: session-app-container
    image: brayohmurithi/session-app
    ports:
      - 5000:5000
    volumes:
      - ./:/app